server:
  port: 10001
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
    mysql:
      username: math
      password: 7891919
      url: jdbc:mysql://127.0.0.1:3308/mathstreak?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat

    pgvector:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 7891919
      url: jdbc:postgresql://193.112.94.229:5434/ai-rag-knowledge
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    openai:
      base-url: https://api.deepseek.com/
      api-key:

  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password: 114514
      database: 1

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

