server:
  port: 10001
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
    mysql:
      username:
      password:
      url: jdbc:mysql://127.0.0.1:3306/mathstreak?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat

    pgvector:
      driver-class-name: org.postgresql.Driver
      username:
      password:
      url: jdbc:postgresql://127.0.0.1:5434/ai-rag-knowledge
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 30000
        connection-timeout: 30000
  ai:
    openai:
      base-url:
      api-key:
      timeout: 120000
      chat:
        model:
  rabbitmq:
    addresses:
    port:
    username:
    password:
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    # 消息配置
    config:
      # 生产者
      producer:
        # 绑定交换机，统一一套交换机
        exchange: math_streak_exchange
        # 消息主题配置；路由key、队列
        topic_status_update:
          # 消息主题
          routing_key: topic.status_update
          # 消费队列
          queue: math_streak_queue_2_topic_status_update

  data:
    redis:
      host:
      port:
      password:
      database: 1

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

